### ISSUE TITLE
Use Kusion WebIDE to provide quick start experience

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/kusionstack.io#175]
### Advantages of the WebIDE (vs local IDE)

- For new users' quick start & playground: Since the installation and the Prerequisites to run the quick-start case and play with kusion are inconvenient for the newly attracted user, webIDE with all the kusion components out-of-box is a good choice.
- For daily use of developing: the web IDE with bundled Kusion environment could be a fair choice, since it has natural advantages for the uniform environment and sharing code through the team, etc.

### Technical feasibility analysis

There are several web IDE products, which have the ability to provide both the online-coding and a container created from the custom image: 
- [github.dev](https://github.dev/github/dev) (paid version)
- ant group's cloud IDE commercial version
- **todo, others**

I‘ve verified the feasibility through Antgroup's cloud IDE, and here's the result:
- The IDE will be firstly released next month.
- The IDE will provide a VS Code style coding interface.
- The IDE can start a workspace with a running container, which can be used to run kusion commands and we already have the kusion image.
- The IDE provides 50 hours of free usage per month for each device. And with 2C4G resources provided freely.
- The container has access to the internet, so applying resources to AWS/Aliyun/... is accessible, users only need to do some configurations to upload the kubeConfig file to the workspace.
- For users without an account of cloud providers, the lightweight [k3s](https://k3s.io/) can be built-in to the kusion image to provide a quick try.

**Comment by amyXia1994** [comment]
### 2022.11.7 goals
•user can try kusion quick start without **any environment pre-request** 
•user can deploy a sample application **with several button clicks without leaving IDE**
•user can successfully complete kusion quick start in **less than 5min**

### break down the goals
- **No need to download and install kusion**: with kusion image provided in the webIDE
- **No k8s environment required**: for users without an account to the public cloud, provide a built-in k3s cluster within the image
- **No need to configure the k8s cluster**: it is configured by default in the image
- **No need to write code from scratch**: provides complete code that can be and opened and run directly with a link
- **No need to type commands for typical operations**: recognize project/stack; encapsulate kusion compile, apply, watch
- **Beginners can quickly know how to use**: provide wizard
- **Easy to repeat the operations**: After the first try, users can sync their configurations by a single click

**Comment by ldxdl** [comment]
Make Kusion quick-start & playground super easy @chai2010 @SparkYuan @Peefy, gogogo:)

**Comment by amyXia1994** [comment]
For `github.dev` webIDE, we need to provide a DevContainer to quickly start up a kusion & minikube dev environment: https://github.com/KusionStack/kusion/issues/163

**Comment by amyXia1994** [comment]
a good ref: rust provides a remote codespace for users to try rust: https://github.com/microsoft/vscode-remote-try-rust

**Comment by amyXia1994** [comment]
github codespace now supports personal use with 200 free core hours of computing usage and 15.00 GB-month storage usage.

billing: https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces
GitHub Codespaces for personal accounts FAQ: https://github.com/orgs/community/discussions/38697
Making the most of your included free Codespaces usage: https://github.com/orgs/community/discussions/39697

**Comment by amyXia1994** [comment]
gitpod as webIDE: https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml
