### ISSUE TITLE
Help us translate the website

### ISSUE THREAD

**Issue by chai2010** [KusionStack/kusionstack.io#25]
1. create a new translate issue, include the page link
2. translate the doc
3. submit the PR

**Comment by amyXia1994** [comment]
the link seems broken:
![image](https://user-images.githubusercontent.com/29722609/196149730-44a0c8cc-4090-4d18-bdf9-baec4d3f6e61.png)

**Comment by chai2010** [comment]
@amyXia1994 we do not use crowdin now, the broken url is removed.
