### ISSUE TITLE
docs: `zh-CN/docs/user_docs` chinese version issue list

### ISSUE THREAD

**Issue by niconical** [KusionStack/kusionstack.io#263]
The following pages lack Chinese version:
- [x] https://kusionstack.io/zh-CN/docs/user_docs/getting-started/usecases/deliver-first-project  #256 
- [x] https://kusionstack.io/zh-CN/docs/user_docs/getting-started/kusion-ide  #256 
- [ ] https://kusionstack.io/zh-CN/docs/user_docs/concepts/konfig
- [ ] https://kusionstack.io/zh-CN/docs/user_docs/concepts/kusion
- [ ] https://kusionstack.io/zh-CN/docs/user_docs/guides/working-with-k8s/service
- [ ] https://kusionstack.io/zh-CN/docs/user_docs/guides/working-with-k8s/resource-spec

**Comment by niconical** [comment]
It seems that many Chinese pages can refer to this book——[kusion-in-action-book](https://github.com/KusionStack/kusion-in-action-book).

**Comment by SparkYuan** [comment]
The Chinese version will be removed.
