### ISSUE TITLE
docs: The KCL whole documentation needs a better organized directory

### ISSUE THREAD

**Issue by Peefy** [KusionStack/kusionstack.io#84]
Need to make key additions on features and scenes.

**Comment by Peefy** [comment]
# (中文版本)

## KCL 介绍
## 基础文档
### KCL 核心特性
### KCL 使用场景
#### 生成静态配置数据如 JSON, YAML 等
#### 使用 schema 对配置数据进行建模并减少配置数据中的样板文件
#### 为配置数据定义带有规则约束的 schema 并对数据进行自动验证
#### 无副作用地组织、简化、统一和管理庞大的配置
#### 通过分块编写配置数据可扩展地管理庞大的配置
#### 与 [Kusion Stack](https://kusionstack.io/) 一起，用作平台工程语言来交付现代应用程序
### 如何选择
## 概念
### Config
### Schema
### Rule
### Lambda
## 进阶文档
### KCL Lang Tour
### KCL CodeLab
### KCL Spec
## 更多参考
### 类型系统
### 模块系统
### 错误和异常
### 多语言支持
### 插件系统

# (English Version)

## KCL Introduction
## Basic Documentation
### KCL Core Features
### KCL Use Cases
#### Generate low-level static configuration data like JSON, YAML, etc.
#### Reduce boilerplate in configuration data with the schema modeling.
#### Define schemas with rule constraints for configuration data and validate them automatically.
#### Organize, simplify, unify and manage large configurations without side effects.
#### Manage large configurations scalably with isolated configuration blocks.
#### Used as a platform engineering lang to deliver modern app with [Kusion Stack](https://kusionstack.io/).
### How to Choose
## Concept
### Config
### Schema
### Rule
### Lambda
## Advanced Documentation
### KCL Lang Tour
### KCL CodeLab
### KCL Spec
## References
### Type System
### Module system
### Errors and exceptions
### Multi-language support
### Plugin system

**Comment by chai2010** [comment]
mv Concept to Advanced Documentation subsection

**Comment by Peefy** [comment]
现代语言方式编写**复杂类型和建模**，维护**可扩展的配置文件**，**原生的纯函数**和**策略**，和**生产级的性能**和**自动化**，建议选择 KCL。从 6 个大的方面阐述，并给出具体的例子

KCL is recommended if you want types and modeling like a modern language, scalable configurations, in-house pure functions and rules, and production-ready performance and automation.
